### ISSUE TITLE
Record limit issue

### ISSUE THREAD

**Issue by cfjedimaster** [pixelastic/algolia-indexing#5]
Let me start off by saying that this is - probably - my fault. 

So my index currently has 6.1k entries. I'm trying to do an atomic update via code like so:

```js
const fetch = require('node-fetch');
const indexing = require('algolia-indexing');
const algCredentials = { appId: process.env.ALG_APP_ID, apiKey: process.env.ALG_API_KEY, indexName: 'raymondcamden' };

// first, get my index
let dataResp = await fetch('https://www.raymondcamden.com/algolia.json');

let data = await dataResp.json();
console.log('Successfully got the data, size of articles '+data.length, data[0].title);

indexing.verbose();

const settings = { };
try {
  await indexing.fullAtomic(algCredentials, data, settings);
} catch(e) {
  console.log('error in fullAtomic', e);
};
 console.log('Algolia indexing updated. Hopefully.');
```

And I get:

```
Unable to copy index raymondcamden to raymondcamden_tmp
✔ Updating settings of raymondcamden_tmp
✔ Getting all records from raymondcamden_manifest
✖ Unable to process batch
ApiError
Record quota exceeded, change plan or delete records.
✖ Unable to process batch
ApiError
Record quota exceeded, change plan or delete records.
✖ Unable to process batch
ApiError
Record quota exceeded, change plan or delete records.
✖ Unable to process batch
ApiError
Record quota exceeded, change plan or delete records.
✖ Unable to process batch
ApiError
Record quota exceeded, change plan or delete records.
```

I'm on the Community plan which has a max of 10k records, but my data is only 6.1k or so.  Ah... wait... is the issue is that it's copied over first and that's hitting my limit?

**Comment by cfjedimaster** [comment]
Dangit, yep, and this is documented:

```
This will update an index with new records and settings in an atomic way. It will be fast but will require a plan with a large number of records (as we'll need to duplicate the index for a short period of time).
```

I guess I'm screwed unless I write my own logic. 

I have to ask - why is the index copied? If atomic updates are done, can't we leave the original and modify it?

**Comment by chrisdmacrae** [comment]
@cfjedimaster atomic updates are done by using a second index to perform all of the transactions (batch updates), and wait until confirmation that their done. Then the atomic update is done by swapping the indices and dropping the second index.

If you were to think about atomic deployments of files, it’s the same thing. 

You’d have an uploads folder, you’d upload each deployment into a time stamped folder, and then symlink the latest deployment to the www folder to swap out that deployment instantaneously.

**Comment by pixelastic** [comment]
Hey, sorry I completely missed this issue.

As Chris is saying, you might be interested in the other package that does it slightly differently. I was planning on implementing such a method at some point into this very own module, but turns out I never actually needed it so chances are I'm not going to implement it any time soon :)

I'm closing this as `atomic-algolia` seems more suited to what you want to do. I'd love to see the two packages merged at some point.
